import { Router } from 'express';
import { db } from '../index.js';
import { validateComplaint } from '../middleware/validation.js';
import { ComplaintController } from '../controllers/complaintController.js';
export const complaintsRouter = Router();
complaintsRouter.get('/', ComplaintController.getAllComplaints);
complaintsRouter.get('/:id', ComplaintController.getComplaintById);
complaintsRouter.post('/', validateComplaint, ComplaintController.createComplaint);
complaintsRouter.put('/:id/status', ComplaintController.updateComplaintStatus);
complaintsRouter.get('/person/:personId', ComplaintController.getComplaintsByPerson);
complaintsRouter.get('/stats/dashboard', ComplaintController.getDashboardStats);
complaintsRouter.post('/:id/assign', ComplaintController.assignComplaint);
complaintsRouter.get('/officer/:officerId', ComplaintController.getComplaintsByOfficer);
complaintsRouter.post('/:id/feedback', ComplaintController.submitFeedback);
complaintsRouter.get('/:id/feedback', ComplaintController.getComplaintFeedback);
complaintsRouter.get('/:id/logs', ComplaintController.getComplaintLogs);
complaintsRouter.post('/:id/updates', ComplaintController.addComplaintUpdate);
complaintsRouter.get('/:id/updates', ComplaintController.getComplaintUpdates);